version: '2.2'
services:
  nginx: 
    image: "pryvsa-docker-release.bintray.io/pryv/nginx:1.2.13"
    networks: 
      - frontend
    ports:
      - "80:80"
      - "443:443"
      - "3443:3443"
    volumes: 
      - ${PRYV_CONF_ROOT}/nginx/conf/:/app/conf/
      - ${PRYV_CONF_ROOT}/nginx/log/:/app/log/
    links: 
      - core
      - preview
      - condensate
    restart: always

  core: 
    image: "pryvsa-docker-release.bintray.io/pryv/core:1.2.19"
    networks: 
      - frontend
      - backend
    volumes: 
      - ${PRYV_CONF_ROOT}/core/conf/:/app/conf/
      - ${PRYV_CONF_ROOT}/core/log/:/app/log/
      - ${PRYV_CONF_ROOT}/core/data/:/app/data/
    links: 
      - mongodb
    restart: always
    hostname: "$HOSTNAME"
    
  preview: 
    image: "pryvsa-docker-release.bintray.io/pryv/preview:1.2.19"
    networks: 
      - frontend
      - backend
    volumes: 
      - ${PRYV_CONF_ROOT}/preview/log/:/app/log/
      - ${PRYV_CONF_ROOT}/preview/conf/:/app/conf/
      # Not an error: Preview accesses core's data directory readonly. 
      - ${PRYV_CONF_ROOT}/core/data/:/app/data/
    links: 
      - mongodb
    restart: always
    hostname: "$HOSTNAME"

  mongodb: 
    image: "pryvsa-docker-release.bintray.io/pryv/mongodb:1.2.13"
    networks: 
      - backend
    volumes: 
      - ${PRYV_CONF_ROOT}/mongodb/conf/:/app/conf/
      - ${PRYV_CONF_ROOT}/mongodb/log/:/app/log/
      - ${PRYV_CONF_ROOT}/mongodb/data/:/app/data/
    restart: always

  condensate:
    image: "pryvsa-docker-release.bintray.io/pryv/condensate:0.0.5"
    networks:
      - frontend
    volumes:
      - ${PRYV_CONF_ROOT}/condensate/conf/:/app/conf/
      - ${PRYV_CONF_ROOT}/condensate/log/:/app/log/
    links:
      - core
    restart: always
    
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
