version: '2.1'
services:
  nginx: 
    image: "pryvsa-docker-release.bintray.io/pryv/nginx:1.2.13"
    networks: 
      - frontend
    ports: 
      - "443:443"
    volumes: 
      - ${PRYV_CONF_ROOT}/nginx/conf/:/app/conf/
      - ${PRYV_CONF_ROOT}/nginx/log/:/app/log/
    links: 
      - static
    restart: always

  static: 
    image: "pryvsa-docker-release.bintray.io/pryv/static:1.2.13"
    volumes: 
      - ${PRYV_CONF_ROOT}/static/conf/:/app/conf/
    networks: 
      - frontend
    restart: always

networks:
  frontend:
    driver: bridge
