#!/usr/bin/env bash

set -e

customer=$1

function build_role() {
  role=$1

  COPYFILE_DISABLE=1 tar -vzcf "tarballs/$customer-$role.tgz" \
    --exclude .DS_Store \
    config-follower run-config-follower stop-config-follower \
    config-leader run-config-leader stop-config-leader \
    pryv run-pryv stop-pryv \
    ensure-permissions \
    INSTALL-single-node.md
}

build_role "singlenode"