version: "3.5"
services:
  config-leader:
    image: "eu.gcr.io/pryvio/config-leader:1.0.25"
    container_name: pryvio_config_leader
    networks:
      - frontend
      - backend
    volumes:
      - ./conf/:/app/conf/
      - ./log/:/app/log/
      - ./data/:/app/data/
      - ./database/:/app/database/
      - credentials-volume:/app/credentials
    restart: always
  ssl-certificate:
    image: "eu.gcr.io/pryvio/ssl-certificate:1.0.5"
    container_name: pryvio_ssl_certificate
    volumes:
      - ./conf/:/app/conf/
      - ./data/:/app/data/
      - ./log/:/app/log/
      - ./letsencrypt:/etc/letsencrypt
      - credentials-volume:/app/credentials
      - ../pryv/dns/conf/dns.json:/app/dns.json
    depends_on:
      - config-leader
    environment:
      - DEBUG=false
    network_mode: "host"
networks:
  frontend:
    driver: bridge
    name: pryv_frontend
  backend:
    driver: bridge
    name: pryv_backend
volumes:
  credentials-volume: