version: "3.5"
services:
  config-leader:
    image: "pryvsa-docker-release.bintray.io/pryv/config-leader:1.0.23"
    container_name: pryvio_config_leader
    networks:
      - frontend
      - backend
    volumes:
      - ./conf/:/app/conf/
      - ./log/:/app/log/
      - ./data/:/app/data/
      - ./database/:/app/database/
      - credentials-volume:/app/credentials
    restart: always
  ssl-certificate:
    image: "pryvsa-docker-release.bintray.io/pryv/ssl-certificate:1.0.0"
    container_name: pryvio_ssl_certificate
    networks:
      - frontend
      - backend
    volumes:
      - ./conf/:/app/conf/
      - ./data/:/app/data/
      - ./letsencrypt:/etc/letsencrypt
      - credentials-volume:/app/credentials
    depends_on:
      - config-leader
networks:
  frontend:
    driver: bridge
    name: pryv_frontend
  backend:
    driver: bridge
    name: pryv_backend
volumes:
  credentials-volume: