version: 1.0.0
domain: pryv.li
extraDomains:
  - pryv.li
redis:
  password: OVERRIDE_ME # password on redis is not necessary now as redis has no public interface when containerized
coreDefaults:
  systemKey: OVERRIDE_ME
dns:
  listeningIp: 0.0.0.0
  listeningPort: 53
  domain_A: 95.142.162.223 # IP address of www.TLD. Should send to service homepage, eg. pryv.com
  entries:
    -
      name: www # should point to same as domainA (above)
      type: alias
      value: stswww-gandi-fr-01.pryv.net
    -
      name: sw # for app-web & pop-up login
      type: alias
      value: stswww-gandi-fr-01.pryv.net
    -
      name: reg
      type: alias
      value: streg-gandi-fr-01.pryv.net
    -
      name: service # useful to store services configuration possibly on a separate machine, currently still on register
      type: alias
      value: streg-gandi-fr-01.pryv.net
    -
      name: access # for login, here for optional splitting, as "service"
      type: alias
      value: streg-gandi-fr-01.pryv.net
    -
      name: bridges
      type: alias
      value: stbridgemulti-amazon-use-01.pryv.net
    -
      name: import # legacy CSV importer
      type: alias
      value: gpaas3.dc0.gandi.net
    -
      name: ifttt
      type: alias
      value: stifttt-amazon-use-01.pryv.net
    -
      name: l # for test purposes, meant to disappear
      type: ip
      value: 127.0.0.1
    -
      name: local # for test purposes, meant to disappear
      type: ip
      value: 127.0.0.1
    -
      name: reglocal # for test purposes, meant to disappear
      type: ip
      value: 127.0.0.1
  nameServers:
    -
      name: streg-gandi-fr-01.pryv.net
      ip: 95.142.162.223
    -
      name: streg-gandi-lu-01.pryv.net
      ip: 213.167.242.177
  server:
    ssl: false
    port: 9000
cores:
  -
    hostnameOrIp: stact-exoscale-ch-01.pryv.net
    hosting: exoscale.ch-ch # must match available entry in "hostings"
  -
    hostnameOrIp: stact-exoscale-ch-02.pryv.net
    hosting: exoscale.ch-ch2
  -
    hostnameOrIp: stcore-azure-euw-01.pryv.net
    hosting: azure.com-nl
hostings:
  regions:
    europe:
      name: Europe
      localizedName:
        fr: Europe
      zones:
        france:
          name: France
          localizedName:
            fr: France
          hostings:
            gandi.net-fr:
              url: 'http://gandi.net'
              name: Gandi
              description: 'No bullshit'
              localizedDescription: {}
        netherlands:
          name: Netherlands
          localizedName:
            fr: 'Pays Bas'
          hostings:
            azure.com-nl:
              url: 'https://azure.microsoft.com/en-us/'
              name: 'Microsoft Azure'
              description: 'The cloud for modern business'
              localizedDescription: {}
        switzerland:
          name: Switzerland
          localizedName:
            fr: Suisse
          hostings:
            exoscale.ch-ch:
              url: 'https://www.exoscale.ch'
              name: Exoscale
              description: 'A safe home - Swiss quality'
              localizedDescription: {}
            exoscale.ch-ch2:
              url: 'https://www.exoscale.ch'
              name: 'Exoscale DSlike'
              description: 'A safe home - Swiss quality'
              localizedDescription: {}
    north-america:
      name: 'North America'
      localizedName:
        fr: 'Amérique du Nord'
      zones:
        usa-east:
          name: 'East-coast USA'
          localizedName:
            fr: 'USA cote est'
          hostings:
            gandi.net-us:
              url: 'http://gandi.net'
              name: Gandi
              description: 'No bullshit'
              localizedDescription: {}
        usa-west:
          name: 'West-coast USA'
          localizedName:
            fr: 'USA cote ouest'
          hostings:
            joyent.net-usw:
              url: 'http://joyent.com'
              name: Joyent
              description: 'High performance'
              localizedDescription: {}
    asia:
      name: Asia
      localizedName:
        fr: Asie
      zones:
        hk:
          name: Hong-Kong
          localizedName: {}
          hostings:
            fengqi.asia-hk:
              url: 'http://fengqi.asia'
              name: Fengqi.asia
              description: 'We Make Your Business Fly'
              localizedDescription: {}
    australia:
      name: 'Australia (Coming soon)'
      localizedName:
        fr: 'Australie (bientôt disponible)'
      zones: {}
mongo:
  host: localhost
  port: 27017
  databaseName: pryv-node
eventTypes:
  sourceURL: 'http://api.pryv.com/event-types/flat.json'
coreApi:
  mongo: # for v1.2 dockerized, we recommend not to use credentials as MongoDB has no public interface
    username: api-server
    password: OVERRIDE_ME
  eventFiles:
    attachmentsDirPath: '/app/data/attachments'
    previewsDirPath: '/app/data/previews'
  http:
    ip: 127.0.0.1
    port: 9000
    noSSL: true
  auth:
    trustedApps: '*@https://*.rec.la*, *@https://*.pryv.li*, *@https://pryv.github.io*'
    browserIdAudience: 'https://{username}.pryv.li:443'
    sessionMaxAge: 1209600000
    ssoCookieDomain: .pryv.li
    ssoCookieSignSecret: OVERRIDE_ME
    filesReadTokenSecret: OVERRIDE_ME
    passwordResetRequestMaxAge: 3600000
    passwordResetPageURL: 'https://sw.pryv.li/access/reset-password.html'
  logs:
    console:
      active: true
      level: info
      colorize: false
    file:
      active: false
      level: error
      path: '/app/log/core.log'
      maxFileBytes: 4096
      maxNbFiles: 20
preview:
  http:
    ip: 127.0.0.1
    port: 10000
    noSSL: true
  mongo: # for v1.2 dockerized, we recommend not to use credentials as MongoDB has no public interface
    username: browser-server
    password: OVERRIDE_ME
  eventFiles:
    attachmentsDirPath: '/app/data/attachments'
    previewsDirPath: '/app/data/previews'
  logs:
    console:
      active: true
      level: info
      colorize: false
    file:
      active: false
      level: error
      path: '/app/log/preview.log'
      maxFileBytes: 4096
      maxNbFiles: 20
  auth:
    sessionMaxAge: 1209600000
swww:
  http:
    port: 9000
    certsPathAndKey: false
    ip: 127.0.0.1
  http2:
    port: 9001
    certsPathAndKey: false
    ip: 127.0.0.1
  browserBootstrap:
    fields:
      browser-source: 'https://sw.pryv.li/browser'
  redirect:
    port: 0
register:
  hostnameOrIP: 'https://reg.pryv.li'
  systemKeys:
    - OVERRIDE_ME
  adminKeys:
    - username1|OVERRIDE_ME
    - username2|OVERRIDE_ME
  http:
    static:
      url: 'https://www.pryv.com' # redirect address from reg.pryv.li
      access: 'https://sw.pryv.li/access/v1/access.html'
    register:
      url: 'https://reg.pryv.li'
  service: # prototype for /service/infos content
    name: 'Pryv Lab staging'
    support: 'mailto:support@pryv.com'
    terms: 'http://pryv.com/terms-of-use/'
  server:
    ssl: 'false'
    ip: 127.0.0.1
    port: 9000
  appList:
    pryv-ios-app:
      displayName: 'Pryv for iOS'
      description: 'Capture and browse pictures, notes, values etc. while on the go'
      iconURL: 'https://sw.pryv.li/apps/pryv-ios-app/icon512.png'
      appURL: 'https://itunes.apple.com/us/app/pryv/id826320447'
      active: false
      onboarding: false
      category: Other
      settingsPageURL: ""
    pryv-csv-importer:
      displayName: 'CSV Importer'
      description: 'Import existing data from CSV files'
      iconURL: 'https://sw.pryv.li/apps/pryv-csv-importer/icon512.png'
      appURL: 'http://pryv.github.io/dev-tools/csv-importer'
      active: false
      onboarding: false
      category: Other
      support:
        - iPad
        - iPhone
        - Web
      settingsPageURL: 'http://pryv.github.io/dev-tools/csv-importer'
    ifttt-all:
      displayName: IFTTT
      description: 'Connect Pryv to over 100 other products and services with Pryv Recipes on IFTTT'
      iconURL: 'https://sw.pryv.li/apps/ifttt-all/icon512.png'
      appURL: 'https://ifttt.com/pryv'
      active:/v false
      onboarding: false
      category: Other
      support:
        - iPad
        - iPhone
        - Web
      settingsPageURL: 'https://ifttt.com/pryv'
    bridge-twitter:
      displayName: Twitter
      description: 'Pryv selected tweets from my <strong>Twitter</strong> account.'
      iconURL: 'https://sw.pryv.li/apps/bridge-twitter/icon512.png'
      appURL: 'https://bridges.pryv.li:4443/'
      active: true
      onboarding: true
      category: Thoughts
      position: 1
      support:
        - iPad
        - iPhone
        - Web
      settingsPageURL: 'https://bridges.pryv.li:4443/'
      trustedConnection: true
    bridge-withings:
      displayName: Withings
      description: 'Pryv my <strong>Withings</strong> measures.'
      iconURL: 'https://sw.pryv.li/apps/bridge-withings/icon512.png'
      appURL: 'http://bridges.pryv.li:5443/'
      active: true
      onboarding: true
      category: 'Health & Activity'
      position: 2
      support:
        - iPad
        - iPhone
        - Web
      settingsPageURL: 'http://bridges.pryv.li:5443/'
      trustedConnection: true
    bridge-misfit:
      displayName: Misfit
      description: 'Pryv activities from my <strong>Misfit Shine</strong>.'
      iconURL: 'https://sw.pryv.li/apps/bridge-misfit/icon512.png'
      appURL: 'https://bridges.pryv.li:6443/'
      active: true
      onboarding: true
      position: 3
      support:
        - iPad
        - iPhone
        - Web
      category: 'Health & Activity'
      settingsPageURL: 'https://bridges.pryv.li:6443/'
      trustedConnection: true
    bridge-moves:
      displayName: Moves
      description: 'Pryv the places I track with the <strong>Moves</strong> app.'
      iconURL: 'https://sw.pryv.li/apps/bridge-moves/icon512.png'
      appURL: 'https://bridges.pryv.li:7443/'
      active: true
      onboarding: true
      category: Location
      position: 3
      support:
        - iPad
        - iPhone
        - Web
      settingsPageURL: 'https://bridges.pryv.li:7443/'
      trustedConnection: true
    bridge-ihealth:
      displayName: iHealth
      description: 'Pryv my health data with <strong>iHealth</strong> app.'
      iconURL: 'https://sw.pryv.li/apps/bridge-ihealth/icon512.png'
      appURL: 'https://bridges.pryv.li:8443/'
      active: true
      onboarding: true
      category: 'Health & Activity'
      position: 3
      support:
        - iPad
        - iPhone
        - Web
      settingsPageURL: 'https://bridges.pryv.li:8443/'
      trustedConnection: true
    pryv-integration-osx:
      displayName: 'Pryv OSX'
      description: 'Integrate Pryv with your desktop'
      iconURL: 'https://sw.pryv.li/apps/pryv-integration-osx/icon512.png'
      appURL: 'https://itunes.apple.com/app/pryv/id881452044'
      active: false
      onboarding: false
      category: Other
      support:
        - iPad
        - iPhone
        - Web
      settingsPageURL: ""
extra:
  dns:
    mail:
      -
        name: spool.mail.gandi.net
        ip: 217.70.184.6
        ttl: 10800
        priority: 10
      -
        name: fb.mail.gandi.net
        ip: 217.70.184.162
        ttl: 10800
        priority: 50
  coreApi:
    services:
      email:
        url: 'https://mandrillapp.com'
        key: OVERRIDE_ME
        sendMessagePath: /api/1.0/messages/send-template.json
        welcomeTemplate: welcome-email
        resetPasswordTemplate: reset-password
  airbrake:
    coreApi:
      active: true
      key: OVERRIDE_ME
    preview:
      active: true
      key: OVERRIDE_ME
    register:
      key: OVERRIDE_ME
