version: '3'
services:

  reverse_proxy: 
    image: "pryvsa-docker-release.bintray.io/pryv/nginx:1.3.36"
    networks: 
      - frontend
    ports: 
      - "80:80"
      - "443:443"
    volumes: 
      - ./core/nginx/conf/:/app/conf/:ro
      - ./core/nginx/log/:/app/log/
    links: 
      - core
      - hfs
      - preview
    restart: always

  core: 
    image: "pryvsa-docker-release.bintray.io/pryv/core:1.3.55"
    networks:
      - frontend
      - backend
    volumes: 
      - ./core/core/conf/:/app/conf/:ro
      - ./core/core/data/:/app/data/
      - ./core/core/log/:/app/log/
    environment: 
      - NUM_PROCS=2
    links: 
      - mongodb
    restart: always

  mail: 
    image: "pryvsa-docker-release.bintray.io/pryv/mail:1.0.3"
    networks: 
      - frontend
    volumes: 
      - ./core/mail/conf/:/app/conf/:ro
      - ./core/mail/templates/:/app/bin/templates/:ro
    restart: always

  preview: 
    image: "pryvsa-docker-release.bintray.io/pryv/preview:1.3.55"
    networks: 
      - frontend
      - backend
    volumes: 
      - ./core/preview/conf/:/app/conf/:ro
      - ./core/core/data/:/app/data/
      - ./core/preview/log/:/app/log/
    links: 
      - mongodb
    restart: always

  hfs:
    image: "pryvsa-docker-release.bintray.io/pryv/hfs:1.3.55"
    networks:
      - frontend
      - backend
    volumes:
      - ./core/hfs/conf/:/app/conf/:ro
      - ./core/hfs/data/:/app/data/
      - ./core/hfs/log/:/app/log/
    environment:
      - NUM_PROCS=2
    links:
      - influxdb
      - mongodb
    restart: always

  mongodb:
    image: "pryvsa-docker-release.bintray.io/pryv/mongodb:1.3.36"
    networks:
      - backend
    volumes:
      - ./core/mongodb/conf/:/app/conf/:ro
      - ./core/mongodb/data/:/app/data/
      - ./core/mongodb/log/:/app/log/
    restart: always

  influxdb:
    image: "influxdb:1.2.2"
    networks:
      - backend
    volumes:
      - ./core/influxdb/data/:/var/lib/influxdb
    restart: always

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
