version: '3'
services:

  reverse_proxy: 
    image: "pryvsa-docker-release.bintray.io/pryv/nginx:1.3.38"
    networks: 
      - frontend
    ports: 
      - "80:80"
      - "443:443"
    volumes: 
      - ./core/nginx/conf/:/app/conf/:ro
      - ./core/nginx/log/:/app/log/
    links: 
      - core
      - hfs
      - preview
      - condensate
    restart: always

  core_router:
    image: "pryvsa-docker-release.bintray.io/pryv/router:1.0.0"
    networks:
      - frontend
    links:
      - core
    environment:
      ROUTER_LOG: info
    volumes:
      - /dev/log:/dev/log
    command: --core-audit core:3000 --core-audit core:3001 --core-audit core:3002 --core-audit core:3003
    restart: always

  core: 
    image: "pryvsa-docker-release.bintray.io/pryv/core:1.4.10-40-gab949b1"
    networks:
      - frontend
      - backend
    volumes: 
      - ./core/core/conf/:/app/conf/:ro
      - ./core/core/data/:/app/data/
      - ./core/core/log/:/app/log/
    environment: 
      - NUM_PROCS=4
      - STARTING_PORT=3000
    links: 
      - mongodb
    restart: always
    hostname: "$HOSTNAME"

  preview: 
    image: "pryvsa-docker-release.bintray.io/pryv/preview:1.4.10-40-gab949b1"
    networks: 
      - frontend
      - backend
    volumes: 
      - ./core/preview/conf/:/app/conf/:ro
      - ./core/core/data/:/app/data/
      - ./core/preview/log/:/app/log/
    links: 
      - mongodb
    restart: always
    hostname: "$HOSTNAME"

  hfs:
    image: "pryvsa-docker-release.bintray.io/pryv/hfs:1.4.10-40-gab949b1"
    networks:
      - frontend
      - backend
    volumes:
      - ./core/hfs/conf/:/app/conf/:ro
      - ./core/hfs/data/:/app/data/
      - ./core/hfs/log/:/app/log/
    environment:
      - NUM_PROCS=2
    links:
      - influxdb
      - mongodb
    restart: always
    hostname: "$HOSTNAME"

  webhooks:
    image: "pryvsa-docker-release.bintray.io/pryv/webhooks:1.4.10-40-gab949b1"
    networks:
      - backend
    volumes: 
      - ./core/core/conf/:/app/conf/:ro
      - ./core/core/log/:/app/log/
    links: 
      - mongodb
    restart: always

  mongodb:
    image: "pryvsa-docker-release.bintray.io/pryv/mongodb:1.3.38"
    networks:
      - backend
    volumes:
      - ./core/mongodb/conf/:/app/conf/:ro
      - ./core/mongodb/data/:/app/data/
      - ./core/mongodb/log/:/app/log/
    restart: always

  influxdb:
    image: "influxdb:1.2.2"
    networks:
      - backend
    volumes:
      - ./core/influxdb/data/:/var/lib/influxdb
    restart: always

  condensate:
    image: "pryvsa-docker-release.bintray.io/pryv/condensate:0.0.5"
    networks:
       - frontend
    volumes:
      - ./core/condensate/conf/:/app/conf/:ro
      
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
