#!/usr/bin/env bash

# stop
docker-compose -f pryv/pryv.yml down

# run
[[ -e pryv/pryv.yml ]] || { echo >&2 "The file ./pryv/pryv.yml was not found in current working directory."; exit 1; }

# Host machine hostname, used by reporting and airbrake
export HOSTNAME=$HOSTNAME

# Uncomment line below to disable contractual information reporting
#export reporting_optOut="true"

echo "Running Pryv/core component."
docker-compose -f pryv/pryv.yml up -d