#!/usr/bin/env bash

[[ -e pryv/pryv.yml ]] || { echo >&2 "The file ./pryv/pryv.yml was not found in current working directory."; exit 1; }

echo "Running Pryv/core component."
docker-compose -f pryv/pryv.yml up -d