#!/usr/bin/env bash

[[ -e config-follower.yml ]] || { echo >&2 "Please cd into the configuration directory before running this script."; exit 1; }

echo "Running Pryv/config-follower component."

docker-compose -f config-follower.yml up -d
