#!/usr/bin/env bash

[[ -e config-follower/config-follower.yml ]] || { echo >&2 "The file ./config-follower/config-follower.yml was not found in current working directory."; exit 1; }

echo "Running Pryv/config-follower component."

# Direcory where application configuration files are supposed to be stored
export PRYV_CONF_ROOT="/var/pryv"

docker-compose -f config-follower/config-follower.yml up -d
