version: '3'
services:
  reverse_proxy:
    image: "pryvsa-docker-release.bintray.io/pryv/nginx:1.3.39"
    networks:
      - frontend
    ports:
      - "443:443"
    volumes:
      - ./static/nginx/conf/:/app/conf/:ro
      - ./static/nginx/log/:/app/log/
    restart: always

networks:
  frontend:
    driver: bridge
