version: "3"

networks:
  loki:

services:
  promtail:
    container_name: promtail
    image: grafana/promtail:2.0.0
    ports:
      - "9080:9080"
    volumes:
      - ${PRYV_CONF_ROOT}/pryv/nginx/log:/var/log
      - ${PRYV_CONF_ROOT}/logging/promtail/conf:/var/conf
    command: -config.file=/var/conf/promtail.yaml
    networks:
      - loki

  loki:
    container_name: loki
    image: grafana/loki:2.0.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ${PRYV_CONF_ROOT}/logging/grafana:/var/lib/grafana
    networks:
      - loki
