#!/usr/bin/env bash

SCRIPT_FOLDER=$(cd $(dirname "$0"); pwd)
cd $SCRIPT_FOLDER/..

set -e

# Builds distribution tarballs for the configuration given by CUSTOMER.
#
#   scripts/build CUSTOMER
#

if [ -z "$1" ]; then
  echo "Please provide a customer name as first argument."
  exit 1
fi

customer=$1
rootDir="tarballs/$customer"
commonFiles="config-follower run-config-follower stop-config-follower restart-config-follower \
  watch-config reload-module \
  pryv run-pryv stop-pryv restart-pryv \
  INSTALL.md UPDATE.md"
leaderUrl="https:\/\/lead.DOMAIN"

function build_cores() {
  filesList="$commonFiles ensure-permissions-core"

  for nbr in $(seq $1)
  do
    build "core$nbr" "$filesList" "$leaderUrl"
  done 
}

function build_reg_master() {
  filesList="$commonFiles ensure-permissions-reg-master \
    config-leader run-config-leader stop-config-leader restart-config-leader"

  build "reg-master" "$filesList" "http:\/\/config-leader:7000"
  generate_internals_secrets
}

function generate_secret() {
  openssl rand -hex 32
}

function generate_internals_secrets() {
  file="$rootDir/reg-master/config-leader/conf/config-leader.json"
  sed -i "" -e "s/\"SECRET\"/\"`generate_secret`\"/g" "$file"
}

function build_reg_slave() {
  filesList="$commonFiles ensure-permissions-reg-slave"

  build "reg-slave" "$filesList" "$leaderUrl"
}

function build_static() {
  filesList="$commonFiles ensure-permissions-static"

  build "static" "$filesList" "$leaderUrl"
}

function replace_leader_url() {
  role=$1
  url=$2
  followerConf="$rootDir/${role}/config-follower/conf/config-follower.json"
  sed -i "" -e "s/LEADER_URL/${url}/g" "$followerConf"
}

function generate_lead_fol_keys() {
  role=$1
  secret=`generate_secret`
  leaderConf="$rootDir/reg-master/config-leader/conf/config-leader.json"
  followerConf="$rootDir/${role}/config-follower/conf/config-follower.json"
  sed -i "" -e "s/FOLLOWER_KEY_${role}/${secret}/g" "$leaderConf"
  sed -i "" -e "s/FOLLOWER_KEY/${secret}/g" "$followerConf"
}

function build() {
  role=$1
  filesList=$2
  leaderUrl=$3
  mkdir -p "$rootDir/$role/" # Create temp folder
  for file in $filesList; do cp -r "$file" "$rootDir/$role/$file"; done
  generate_lead_fol_keys "$role"
  replace_leader_url "$role" "$leaderUrl"
}

function prepare_tar() {
  cd $rootDir
  for role in *
  do
    if [[ -d $role ]]; then
      COPYFILE_DISABLE=1 tar -vzcf "$customer-$role.tgz" \
        --exclude .DS_Store \
        "$role"
      rm -r $role # Clean temp folder
    fi
  done
}

build_reg_master # Always build reg-master (leader) first
build_reg_slave
build_cores 2
build_static 

prepare_tar
