#!/usr/bin/env bash

SCRIPT_FOLDER=$(cd $(dirname "$0"); pwd)
cd $SCRIPT_FOLDER/.. # pryv.io

set -e

# Builds distribution tarballs for the configuration given by DOMAIN.
#
#   scripts/build DOMAIN
#

domain=$1

function build_role() {
  role=$1
  filesList="config-follower run-config-follower stop-config-follower \
    pryv run-pryv stop-pryv \
    ensure-permissions-${role} \
    delete-user.md \
    README.md \
    INSTALL.md"

  # Add config-leader files for reg-master only
  if [ $role == "reg-master" ]; then
    filesList+=" config-leader run-config-leader stop-config-leader \
        watch-config reload-module install-fswatch"
  fi

  COPYFILE_DISABLE=1 tar vzcf "tarballs/$domain-$role.tgz" \
    --exclude .DS_Store \
    $filesList
}

build_role "static"
build_role "reg-master"
build_role "reg-slave"
build_role "core"