#!/usr/bin/env bash

set -e

# Builds distribution tarballs for the configuration given by DOMAIN.
#
#   scripts/build DOMAIN
#

domain=$1

function build_role() {
  role=$1

  COPYFILE_DISABLE=1 tar vzcf "$domain-$role.tgz" \
    --exclude .DS_Store \
    $role.yml $role run-$role restart-$role
}

build_role "static"
build_role "reg"
build_role "core"
