{
 "title": "Loki v2 Web Analytics Dashboard for NGINX",
 "description": "Loki v2+ showcase using JSON NGINX access logs.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": "label_values({filename=~`.*json_access.log.*`}, host)"
   }
  ]
 },
 "panels": [
  { "title": "KPI's", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total requests  ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({filename=~`.*json_access.log.*`, host=\"$host\"}[$__interval]))  "
    }
   ]
  },
  {
   "title": "Requests per status code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({filename=~`.*json_access.log.*`, host=\"$host\"} | json |  __error__=\"\" [$__interval]))",
     "legendFormat": "HTTP Status: {{status}}"
    }
   ]
  },
  {
   "title": "% of 5xx requests ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=~`.*json_access.log.*`, host=\"$host\"} | json | status >= 500 |__error__=\"\"[$__interval])) / (sum(count_over_time({filename=~`.*json_access.log.*`, host=\"$host\"} | json | __error__=\"\"[$__interval]))/ 100)"
    }
   ]
  },
  {
   "title": "% of requests by Googlebot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": " sum(count_over_time(({job=\"nginx_access_log\", host=\"$host\"} |= \"Googlebot\")[$__interval])) / (sum(count_over_time(({job=\"nginx_access_log\", host=\"$host\"} != \"Googlebot\")[$__interval])) / 100)"
    }
   ]
  },
  {
   "title": "NGINX logs queried for this period in bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "bytes_over_time({filename=~`.*json_access.log.*`, host=\"$host\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Unique users right now",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by (remote_addr) (count_over_time({filename=~`.*json_access.log.*`, host=\"$host\"} | json |  __error__=\"\" [$__interval])))"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (host) (sum_over_time({filename=~`.*json_access.log.*`, host=\"$host\"} | json | unwrap body_bytes_sent |  __error__=\"\" [$__interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "# NGINX log lines queried for this period",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({filename=~`.*json_access.log.*`, host=\"$host\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Requests per Country",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 9 },
   "valueName": "total",
   "targets": [
    {
     "expr": "sum by (geoip_country_code) (count_over_time({filename=~`.*json_access.log.*`, host=\"$host\"} | json | geoip_country_code != \"\" | __error__=\"\" [$__interval]))",
     "legendFormat": "{{geoip_country_code}}"
    }
   ]
  },
  {
   "title": "Recent requests",
   "type": "logs",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 9 },
   "targets": [
    {
     "expr": "{filename=~`.*json_access.log.*`, host=\"$host\"} | json | line_format \"request for {{.request_uri}} with HTTP status: {{.status}} \""
    }
   ]
  },
  { "title": "Request statistics over time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "95th percentile of Request Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "quantile_over_time(0.95,{filename=~`.*json_access.log.*`, host=\"$host\"} | json | unwrap request_time |  __error__=\"\"  [$__interval]) by (host)",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "max by (host) (max_over_time({filename=~`.*json_access.log.*`, host=\"$host\"} | json | unwrap request_time |  __error__=\"\"  [$__interval]))",
     "legendFormat": "max latency"
    }
   ]
  },
  {
   "title": "HTTP status codes over time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({filename=~`.*json_access.log.*`, host=\"$host\"} | json |  __error__=\"\" [$__interval]))",
     "legendFormat": "HTTP Status {{status}}"
    }
   ]
  },
  {
   "title": "Bytes Sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (sum_over_time({filename=~`.*json_access.log.*`, host=\"$host\"} | json | status=200 | unwrap body_bytes_sent |  __error__=\"\" [$__interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  { "title": "Acquisition and Behaviour", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Top HTTP Referers",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "topk(100, sum by (http_referer) (count_over_time({filename=~`.*json_access.log.*`, host=\"$host\"} | json |  http_referer != \"\" and http_referer !~ \".*?$host.*?\" and http_referer !~ \".*?\\\\*\\\\*\\\\*.*?\" | __error__=\"\" [$__interval])))",
     "legendFormat": "{{http_referer}}"
    }
   ]
  },
  {
   "title": "Top User Agents",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 30 },
   "targets": [
    {
     "expr": "topk(100, sum by (http_user_agent) (count_over_time({filename=~`.*json_access.log.*`, host=\"$host\"} | json |  __error__=\"\" [$__interval])))",
     "legendFormat": "{{http_user_agent}}"
    }
   ]
  },
  {
   "title": "Top IPs",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "topk(100, sum by (remote_addr, geoip_country_code) (count_over_time({filename=~`.*json_access.log.*`, host=\"$host\"} | json |  __error__=\"\" [$__interval])))",
     "legendFormat": "{{remote_addr}}"
    }
   ]
  },
  {
   "title": "Top Requested Pages",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 36 },
   "targets": [
    {
     "expr": "topk(300, sum by (request_uri) (count_over_time({filename=~`.*json_access.log.*`, host=\"$host\"} !~ `\\.ico|\\.svg|\\.css|\\.png|\\.txt|\\.js|\\.xml` | json | status = 200 and request_uri != \"/\" | __error__=\"\" [$__interval])))",
     "legendFormat": "{{request_uri}}"
    }
   ]
  }
 ]
}