#!/usr/bin/env bash

set -e


function build_role() {
  role="pryv"
  
  tar czf "pryv-single-node.tgz" \
    $role.yml  \
    $role \
    run-$role \
    stop-containers \
    delete-user.md \
    ensure-permissions
}

build_role "pryv"