
version: '3'
services:
  reverse_proxy:
    image: "pryvsa-docker-release.bintray.io/pryv/nginx:1.3.38"
    networks:
      - frontend
    ports:
      - "443:443"
    volumes:
      - ./pryv/nginx/conf/:/app/conf/:ro
      - ./pryv/nginx/log/:/app/log/
    links:
      - core
      - hfs
      - preview
      - register
    restart: always

  # Register role START --------------------------------------------------------
  register:
    image: "pryvsa-docker-release.bintray.io/pryv/register:1.3.47"
    networks:
      - frontend
      - backend
    volumes:
      - ./pryv/register/conf/:/app/conf/:ro
      - ./pryv/register/log/:/app/log/
    links:
      - core # This is special to the single config
      - redis
    restart: always

  dns:
    image: "pryvsa-docker-release.bintray.io/pryv/dns:1.3.47"
    ports:
      - "53:5353/udp"
    networks:
      - backend
    volumes:
      - ./pryv/dns/conf/:/app/conf/:ro
      - ./pryv/dns/log/:/app/log/
    links:
      - redis
    restart: always

  redis:
    image: "pryvsa-docker-release.bintray.io/pryv/redis:1.3.38"
    networks:
      - backend
    volumes: 
      - ./pryv/redis/conf/:/app/conf/:ro
      - ./pryv/redis/data/:/app/data/
      - ./pryv/redis/log/:/app/log/
    restart: always
  # Register role END ----------------------------------------------------------

  # Core role START ------------------------------------------------------------
  core:
    image: "pryvsa-docker-release.bintray.io/pryv/core:1.4.20"
    networks:
      - frontend
      - backend
    volumes:
      - ./pryv/core/conf/:/app/conf/:ro
      - ./pryv/core/data/:/app/data/
      - ./pryv/core/log/:/app/log/
    environment: 
      - NUM_PROCS=2
      - STARTING_PORT=3000
    links:
      - mongodb
      - mail
    restart: always

  core_router:
    image: "pryvsa-docker-release.bintray.io/pryv/router:1.0.6"
    networks:
      - frontend
    links:
      - core
    environment:
      ROUTER_LOG: info
    volumes:
      - /dev/log:/dev/log
    command: --core-audit core:3000 --core-audit core:3001
    restart: always

  core_audit:
    image: "pryvsa-docker-release.bintray.io/pryv/audit:1.0.3"
    networks:
      - frontend
    links:
      - core
    volumes:
      - ./core/audit/conf/:/app/conf/:ro
      - ./core/audit/log/:/app/log/
      - /var/log/pryv/audit/pryvio_core/:/app/data/
    restart: always

  mail: 
    image: "pryvsa-docker-release.bintray.io/pryv/mail:1.1.3"
    networks: 
      - frontend
    volumes: 
      - ./pryv/mail/conf/:/app/conf/:ro
      - ./pryv/mail/templates/:/app/bin/templates/:ro
    restart: always

  hfs: 
    image: "pryvsa-docker-release.bintray.io/pryv/hfs:1.4.20"
    networks: 
      - frontend
      - backend
    volumes: 
      - ./pryv/hfs/conf/:/app/conf/:ro
      - ./pryv/hfs/data/:/app/data/
      - ./pryv/hfs/log/:/app/log/
    environment: 
      - NUM_PROCS=2
    links: 
      - influxdb
      - mongodb
    restart: always
  
  webhooks:
    image: "pryvsa-docker-release.bintray.io/pryv/webhooks:1.4.17"
    networks:
      - backend
    volumes: 
      - ./pryv/webhooks/conf/:/app/conf/:ro
      - ./pryv/webhooks/log/:/app/log/
    links: 
      - mongodb
    restart: always

  preview:
    image: "pryvsa-docker-release.bintray.io/pryv/preview:1.4.20"
    networks:
      - frontend
      - backend
    volumes:
      - ./pryv/preview/conf/:/app/conf/:ro
      - ./pryv/core/data/:/app/data/
      - ./pryv/preview/log/:/app/log/
    links:
      - mongodb
    restart: always

  mongodb: 
    image: "pryvsa-docker-release.bintray.io/pryv/mongodb:1.3.38"
    networks: 
      - backend
    volumes: 
      - ./pryv/mongodb/data/:/app/data/
      - ./pryv/mongodb/log/:/app/log/
      - ./pryv/mongodb/backup/:/app/backup/
    restart: always

  influxdb: 
    image: "influxdb:1.7.8"
    networks: 
      - backend
    volumes: 
      - ./pryv/influxdb/data/:/var/lib/influxdb
      - ./pryv/influxdb/backup/:/pryv/backup/
    restart: always
  # Core role END --------------------------------------------------------------

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
