
version: '2.1'
services:
  dns:
    image: "pryvsa-docker-release.bintray.io/pryv/dns:1.2.21"
    ports:
      - "53:5353/udp"
    networks:
      - frontend
      - backend
    volumes:
      - ${PRYV_CONF_ROOT}/dns/conf/:/app/conf/
    links:
      - redis
    restart: always

  nginx:
    image: "pryvsa-docker-release.bintray.io/pryv/nginx:1.2.13"
    networks:
      - frontend
    ports:
      - "443:443"
      - "3443:3443"
    volumes:
      - ${PRYV_CONF_ROOT}/nginx/conf/:/app/conf/
      - ${PRYV_CONF_ROOT}/nginx/log/:/app/log/
    links:
      - core
      - preview
      - register
    restart: always

  register:
    image: "pryvsa-docker-release.bintray.io/pryv/register:1.2.21"
    networks:
      - frontend
      - backend
    volumes:
      - ${PRYV_CONF_ROOT}/register/conf/:/app/conf/
    links:
      - core # This is special to the single config
      - redis
    restart: always

  redis:
    image: "pryvsa-docker-release.bintray.io/pryv/redis:1.2.13"
    networks:
      - backend
    restart: always

  core:
    image: "pryvsa-docker-release.bintray.io/pryv/core:1.2.20"
    networks:
      - frontend
      - backend
    volumes:
      - ${PRYV_CONF_ROOT}/core/conf/:/app/conf/
      - ${PRYV_CONF_ROOT}/core/data/:/app/data/
    links:
      - mongodb
    restart: always

  preview:
    image: "pryvsa-docker-release.bintray.io/pryv/preview:1.2.20"
    networks:
      - frontend
      - backend
    volumes:
      - ${PRYV_CONF_ROOT}/preview/conf/:/app/conf/
      - ${PRYV_CONF_ROOT}/core/data/:/app/data/
    links:
      - mongodb
    restart: always

  mongodb:
    image: "pryvsa-docker-release.bintray.io/pryv/mongodb:1.2.13"
    networks:
      - backend
    restart: always

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
