#!/usr/bin/env bash

[[ -e config-follower/config-follower.yml ]] || { echo >&2 'Please run this script from withing the ${PRYV_CONF_ROOT} directory.'; exit 1; }

echo "Running Pryv/config-follower component."

docker-compose -f config-follower/config-follower.yml up -d
