#!/usr/bin/env bash

[[ -e pryv/pryv.yml ]] || { echo >&2 'Please run this script from withing the ${PRYV_CONF_ROOT} directory.'; exit 1; }

echo "Running Pryv/core component."
docker-compose -f pryv/pryv.yml up -d