#!/usr/bin/env bash

[[ -e config-leader/config-leader.yml ]] || { echo >&2 'Please run this script from withing the ${PRYV_CONF_ROOT} directory.'; exit 1; }

echo "Running Pryv/config-leader component."
docker-compose -f config-leader/config-leader.yml up -d
