version: 1.0.0
domain: DOMAIN
extraDomains:
  - DOMAIN
redis:
  password:
coreDefaults:
  systemKey: CORE_SYSTEM_KEY
dns:
  listeningIp: 0.0.0.0
  listeningPort: 53
  domain_A: SERVICE_WEBSITE_IP_ADDRESS
  entries:
    -
      name: www
      type: alias
      value: SERVICE_WEBSITE_IP_ADDRESS
    -
      name: sw
      type: alias
      value: STATIC_WEB_HOSTNAME
    -
      name: reg
      type: alias
      value: REG_MASTER_HOSTNAME
    -
      name: service
      type: alias
      value: REG_MASTER_HOSTNAME
    -
      name: access
      type: alias
      value: REG_MASTER_HOSTNAME
  nameServers:
    -
      name: REG_MASTER_HOSTNAME
      ip: REG_MASTER_IP_ADRESS
    -
      name: REG_SLAVE_HOSTNAME
      ip: REG_SLAVE_IP_ADRESS
  mail:
    -
       name: 'spool.mail.gandi.net'
       ip: '217.70.184.6'
       ttl: 10800
       priority: 10
    -
       name: 'fb.mail.gandi.net'
       ip: '217.70.184.162'
       ttl: 10800
       priority: 50
  server:
    ssl: false
    port: 9000
cores:
  -
    hostnameOrIp: CORE_1_HOSTNAME_OR_IP
    hosting: CORE_HOSTING_1
  -
    hostnameOrIp: CORE_2_HOSTNAME_OR_IP
    hosting: CORE_HOSTING_1
hostings:
  regions:
    europe:
      name: Europe
      localizedName:
        fr: Europe
      zones:
        switzerland:
          name: Switzerland
          localizedName:
            fr: 'Suisse'
          hostings:
            CORE_HOSTING_1:
              url: 'https://hosting-provider.com'
              name: 'Hosting provider name'
              description: 'Hosting provider slogan'
              localizedDescription: {}
mongo:
  host: localhost
  port: 27017
  databaseName: pryv-node
eventTypes:
  sourceURL: 'http://api.pryv.com/event-types/flat.json'
coreApi:
  mongo:
    username: api-server
  eventFiles:
    attachmentsDirPath: /app/data/api-server-files/attachments
    previewsDirPath: /app/data/api-server-files/previews
  http:
    ip: 127.0.0.1
    port: 9000
    noSSL: true
  auth:
    trustedApps: '*@https://*.rec.la*, *@https://*.DOMAIN*, *@https://pryv.github.io*'
    browserIdAudience: 'https://{username}.DOMAIN:443'
    sessionMaxAge: 1209600000
    ssoCookieDomain: .DOMAIN
    ssoCookieSignSecret: OVERRIDE_ME
    filesReadTokenSecret: OVERRIDE_ME
    passwordResetRequestMaxAge: 3600000
    passwordResetPageURL: 'https://sw.DOMAIN/access/reset-password.html'
  audit:
    forceKeepHistory: true
    deletionMode: 'keep-authors'
  logs:
    console:
      active: false
    file:
      active: true
      level: info
      path: /app/log/core.log
      maxFileBytes: 10000000000
      maxNbFiles: 1
  updates:
    ignoreProtectedFields: false
preview:
  http:
    ip: 127.0.0.1
    port: 10000
    noSSL: true
  mongo:
    username: browser-server
  eventFiles:
    attachmentsDirPath: /app/data/api-server-files/attachments
    previewsDirPath: /app/data/api-server-files/previews
  logs:
    console:
      active: false
    file:
      active: true
      level: info
      path: /app/log/preview.log
      maxFileBytes: 10000000000
      maxNbFiles: 1
  auth:
    sessionMaxAge: 1209600000
swww:
  http:
    port: 9000
    certsPathAndKey: false
    ip: 127.0.0.1
  http2:
    certsPathAndKey: false
  browserBootstrap:
    fields:
      browser-source: 'https://sw.DOMAIN/browser'
  redirect:
    port: 0
register:
  hostnameOrIP: 'https://reg.DOMAIN'
  systemKeys:
    - REGISTER_SYSTEM_KEY_1
  adminKeys:
    - REGISTER_ADMIN_KEY_1
  http:
    static:
      url: 'https://www.COMPANY_WEBSITE'
      access: 'https://sw.DOMAIN/access/access.html'
    register:
      url: 'https://reg.DOMAIN'
  service:
    name: 'PLATFORM_NAME'
    support: 'SUPPORT_LINK_IF_ANY'
    terms: 'TERMS_OF_USE_LINK_IF_ANY'
  server:
    ssl: 'false'
    ip: 127.0.0.1
    port: 9000
extra:
  dns:
    mail:
      -
        name: spool.mail.gandi.net
        ip: 217.70.184.6
        ttl: 10800
        priority: 10
      -
        name: fb.mail.gandi.net
        ip: 217.70.184.162
        ttl: 10800
        priority: 50
  coreApi:
    services:
      email:
        url: 'https://mandrillapp.com'
        key: RcVRdxyEdBTqfE1aMw-W9g
        sendMessagePath: /api/1.0/messages/send-template.json
        welcomeTemplate: welcome-email
        resetPasswordTemplate: reset-password
        enabled:
          welcome: false
          resetPassword: true
  airbrake:
    coreApi:
      active: false
    preview:
      active: false
    register:
      disable: true
    dns:
      disable: true
