#!/usr/bin/env bash

# Directory where application configuration files are supposed to be stored
export PRYV_CONF_ROOT="/var/pryv"

[[ -e ${PRYV_CONF_ROOT}/config-leader/config-leader.yml ]] || { echo >&2 "The file ${PRYV_CONF_ROOT}/config-leader/config-leader.yml was not found."; exit 1; }

echo "Running Pryv/config-leader component."
docker-compose -f ${PRYV_CONF_ROOT}/config-leader/config-leader.yml up -d
