#!/usr/bin/env bash

[[ -e pryv/pryv.yml ]] || { echo >&2 "The file ./pryv/pryv.yml was not found in current working directory."; exit 1; }

# Host machine hostname, used by reporting and airbrake
export HOSTNAME=$HOSTNAME

# Direcory where application configuration files are supposed to be stored
export PRYV_CONF_ROOT="/var/pryv"

# Uncomment line below to disable contractual information reporting
#export reporting_optOut="true"

echo "Running Pryv/core component."
docker-compose -f pryv/pryv.yml up -d