
version: '2.1'
services:
  dns: 
    image: "pryvsa-docker-release.bintray.io/pryv/dns:1.2.19"
    ports: 
      - "53:5353/udp"
    networks: 
      - frontend
      - backend
    volumes: 
      - ${PRYV_CONF_ROOT}/dns/conf/:/app/conf/
    links: 
      - redis
      
  nginx: 
    image: "pryvsa-docker-release.bintray.io/pryv/nginx:1.2.13"
    networks: 
      - frontend
    ports: 
      - "443:443"
      - "3443:3443"
    volumes: 
      - ${PRYV_CONF_ROOT}/nginx/conf/:/app/conf/
      - ${PRYV_CONF_ROOT}/nginx/log/:/app/log/
    links: 
      - core
      - preview
      - static
      - register
      
  register: 
    image: "pryvsa-docker-release.bintray.io/pryv/register:1.2.19"
    networks: 
      - frontend
      - backend
    volumes: 
      - ${PRYV_CONF_ROOT}/register/conf/:/app/conf/
    links: 
      - core # This is special to the single config
      - redis
      
  redis: 
    image: "pryvsa-docker-release.bintray.io/pryv/redis:1.2.13"
    networks: 
      - backend
      
  static: 
    image: "pryvsa-docker-release.bintray.io/pryv/static:1.2.13"
    volumes: 
      - ${PRYV_CONF_ROOT}/static/conf/:/app/conf/
    networks: 
      - frontend
  
  core: 
    image: "pryvsa-docker-release.bintray.io/pryv/core:1.2.19"
    networks: 
      - frontend
      - backend
    volumes: 
      - ${PRYV_CONF_ROOT}/core/conf/:/app/conf/
      - ${PRYV_CONF_ROOT}/core/data/:/app/data/
    links: 
      - mongodb
    
  preview: 
    image: "pryvsa-docker-release.bintray.io/pryv/preview:1.2.19"
    networks: 
      - frontend
      - backend
    volumes: 
      - ${PRYV_CONF_ROOT}/preview/conf/:/app/conf/
      - ${PRYV_CONF_ROOT}/core/data/:/app/data/
    links: 
      - mongodb
      
  mongodb: 
    image: "pryvsa-docker-release.bintray.io/pryv/mongodb:1.2.13"
    networks: 
      - backend
    
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
