name: Pryv.io config template publish

on: 
  push:
    tags:
      - '*'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download master branch
      uses: actions/checkout@v2

    - name: Publish templates
      uses: 2JamesIves/github-pages-deploy-action@4.0.0
      with:
        branch: master # The branch the action should deploy to.
        folder: docs # The folder the action should deploy.