#!/usr/bin/env bash

SCRIPT_FOLDER=$(cd $(dirname "$0"); pwd)
cd $SCRIPT_FOLDER/.. # pryv.io

set -e

# Builds distribution tarballs for the configuration given by DOMAIN.
#
#   scripts/build DOMAIN
#

domain=$1

function build_role() {
  role=$1

  COPYFILE_DISABLE=1 tar vzcf "tarballs/$domain-$role.tgz" \
    --exclude .DS_Store \
    $role.yml $role run-$role stop-containers
}

build_role "static"
build_role "reg-master"
build_role "reg-slave"
build_role "core"
